In [1]:
############ ---------- Speaking Order Generator ---------- ############
import pandas as pd

In [20]:
# Data
data = pd.read_csv('budget_committee_members.csv')
data["Member"] = data["Member"].str.split(" ")
data["Member"] = data["Member"].apply(lambda x: x[1])
data.head()

       Member           State Party  Rank
0   Arrington           Texas     R     1
1      Norman  South Carolina     R     2
2  McClintock      California     R     3
3    Grothman       Wisconsin     R     4
4     Smucker    Pennsylvania     R     5

In [24]:
"D" < "R"

True

In [53]:
def speaking_order(present, data):
    # Filter data for present members
    data = data[data['Member'].isin(present)]
    
    # Sort Republicans and Democrats by rank
    republicans = data[data['Party'] == 'R'].sort_values('Rank')
    democrats = data[data['Party'] == 'D'].sort_values('Rank')
    
    # Interleave Republicans and Democrats
    order = {"Speaker" : [], "Party" : [], "Rank":[], "State":[]}
    for i in range(max(len(republicans), len(democrats))):
        if i < len(republicans):
            order["speaker"].append(republicans.iloc[i]['Member'])
            order["party"].append(republicans.iloc[i]['Party'])
            order["rank"].append(republicans.iloc[i]['Rank'])
            order["state"].append(republicans.iloc[i]['State'])
        if i < len(democrats):
            order["speaker"].append(democrats.iloc[i]['Member'])
            order["party"].append(democrats.iloc[i]['Party'])
            order["rank"].append(democrats.iloc[i]['Rank'])
            order["state"].append(democrats.iloc[i]['State'])
    order = pd.DataFrame(order)
    
    return order

In [51]:
present = ["Arrington", "McClintock", "Smucker", "Boyle", "Schakowsky", "Blumenaeur", "Doggett", "Valadao", "Estes", "Burgess", "Wexton", "McClain", "Peters"]
order = speaking_order(present, data)

       speaker party  rank         state
0    Arrington     R     1         Texas
1        Boyle     D     1  Pennsylvania
2   McClintock     R     3    California
3   Schakowsky     D     2      Illinois
4      Smucker     R     5  Pennsylvania
5       Peters     D     5    California
6      Burgess     R     6         Texas
7      Doggett     D     7         Texas
8      Valadao     R    13    California
9       Wexton     D     9      Virginia
10       Estes     R    14        Kansas
11     McClain     R    15      Michigan